### ISSUE TITLE
How to test the PN7150 with this app ?

### ISSUE THREAD

**Issue by titusece** [NXP/nfc-linux_NfcFactoryTestApp#1]
Hello,
Can you please tell me how can I test this PN7150 NFC ?

Can I place RFID tag on my PN7150 device ?

```
root@imx6:/linux_NfcFactoryTestApp# ./NfcFactoryTestApp

----------------------------
pn54x_dev_open : 10,62
NFC Factory Test Application
---pn54x_dev_ioctl, cmd=1074063617, arg=0
-------------------------
pn544_disable power off
pn54x_dev_ioctl, cmd=1074063617, arg=1
pn544_enable power on
Titus : RFID interrupt is raised!
PN7150 NFC controller detected
Titus : RFID interrupt is raised!
Select the test to run:
         1. Continuous RF ON
         2. PRBS
         3. Standby mode
Your choice:
```

**Comment by jgeslin** [comment]
Hi,

As depicted in related ReadeMe file, the NfcFactoryTestApp purpose it PN71xx characterisation.
It only provides following modes: 
-     Constant RF emission mode (no modulation)
-     or PRBS (Pseudo Random Binary Sequence) mode (continuous modulation)
-     Standby mode
So tapping a card will have basically no impact in any of the 3 modes.

Regards,
Jeremy.

**Comment by titusece** [comment]
Thanks Jeremy for your quick & kind support.
